### ISSUE TITLE
Crash on Doom, Final Doom and Mortal Kombat Trilogy

### ISSUE THREAD

**Issue by billy-acuna** [libretro/pcsx_rearmed_switch#1]
The crash happens before you reach to the title screen on the 3 games, happens on both PBP and CUE format. I cannot reproduce this issue on the PC version, so this belongs to this switch fork.

**Comment by natinusala** [comment]
Could you use nxlink to grab some logs ?

**Comment by billy-acuna** [comment]
Hi @natinusala
I cannot use nxlink any time soon because my modem hates my Switch, so if someone else give it a shot would be apreciated

**Comment by m4xw** [comment]
@billy-acuna We need a crash dump and a log for those Issues

**Comment by bottmint** [comment]
Each of these games have more than 5 bins. Trying to load a cue for a game with more than 5 bins is known to crash the switch. However, when loading Doom and Final Doom via the 1st bin, they seemed to hang on the loading screen. Mortal Kombat Trilogy was able to get in game by loading the 1st bin. All three games were NTSC-U region, and were tested with the relevant NTSC-U bios, per the pcsx_rearmed wiki entry.

Results of loading Doom via cue file: https://hastebin.com/umaqenogeh.cs
Loading Doom via 1st bin: https://hastebin.com/recedenoqo.cs
Loading Final Doom via 1st bin: https://hastebin.com/aveyekinaf.cs
Loading Mortal Kombat Trilogy via 1st bin: https://hastebin.com/ihirebawon.cs

**Comment by Ploggy** [comment]
Has there been any progress made with this issue? 
With the HOS overclock patches coming soon it would be great to get the PS1 game compatibility up too :)
