### ISSUE TITLE
Enable DYNAREC

### ISSUE THREAD

**Issue by yshui** [libretro/pcsx_rearmed_switch#2]
Sorry, but I'm just curious: why is dynrec not enabled? Is there any technical difficulties? Or just not enough manpower to work on it?

**Comment by m4xw** [comment]
There is no aarch64 dynarec.
So, we could use aarch32 execution mode on the Switch, but it wouldn't work with current libraries used (libnx) and would need a major rewrite.
The dynarec has over 15k lines of code, it's not simple to port it. PCSX was only a  small portion of the 40+ Cores we ported, so yea a dynarec wasn't a option, thats why we went with a updated unai renderer and make heavy use of vectorization.
If you wan't to take that part on, be my guest.
I rather get mupen updated in the meantime

**Comment by m4xw** [comment]
Fwiw we have a bounty for a n64 dynarec going https://www.bountysource.com/issues/63766562-write-an-arm64-dynarec
If you want, create another bounty?

**Comment by yshui** [comment]
@m4xw I understand you won't be working on dynarec for the time being, that is fine. But I think we probably can keep this issue open, so others interested can get some information here.

> we could use aarch32 execution mode on the Switch, but it wouldn't work with current libraries used (libnx) and would need a major rewrite.

I assume you mean there is no support for aarch32 execution mode in current libnx? So, is there anything planned in the direction in libnx, or is this unlikely to happen?

> The dynarec has over 15k lines of code, it's not simple to port it.

So to get dynarec working, we need to port it so it generates aarch64 instructions, is that correct?

**Comment by yshui** [comment]
Read some document on aarch64, I guess it is not reasonable to expect aarch32 running on switch then...
