### ISSUE TITLE
[PR]Build fixes some devices/platforms

### ISSUE THREAD

**Issue by ghost** [libretro/pcsx_rearmed_switch#3]
Hi. sent PR for build fix for android, linux (x64) and 3DS. these were tested using related libretro-build-(platform).sh scripts. personally tested the linux build, armeabi (the only one that uses unai). i have no way to test gameplay of 3DS, but since its uses the same files for armeabi, it probably should work as well.

i like the unai here. it doesnt have that wavy, misaligned text borders like the notaz:pcsx_rearmed does though some configurable options doesnt seem to work now (or hooked up and or is has different name)

of course, its just a "just incase you need it" hope this do not break switch

**Comment by m4xw** [comment]
I will check it when I find time, actually I planned to eventually backport it, but so much other things to do.
