### ISSUE TITLE
RetroAchievements Are Not Working

### ISSUE THREAD

**Issue by WasabiIceCream** [libretro/pcsx_rearmed_switch#9]
##Description

When launching a RetroAchievements supported game, the core detects the supported achievements, but performing the required actions will not cause them to pop.

##Steps to reproduce

Been testing with Castlevania: Symphony of the Night, and Spyro the Dragon, because they're 2 games with very easy achievements early on. In Castlevania, just kill Dracula in the start, and the achievement is supposed to pop. With Spyro, just collect 100 gems, and free the 4 dragons in the starting level, and the achievement should pop.

##When did the behavior start?

Tested with earliest nightly build I could grab r22 7375bf9 (09/16/2019), latest stable build r22 7375bf9 (11/02/2019), and latest nightly builds r22 7375bf9 (12/11/2019). None of them pop achievements.
Builds from 12/12/2019 through 12/15/2019 list all achievements as "Unsupported".
Tested against Windows and Android build r22 4b353f8, which works fine.

##Your device/OS/platform/architecture

Nintendo Switch (libnx). [logs.zip](https://github.com/libretro/pcsx_rearmed_switch/files/3966563/logs.zip)
Works fine on Windows and Android.

**Comment by m4xw** [comment]
I no longer support this core since it's no longer possible to rebase it on upstream
